### ISSUE TITLE
Automatically update tours when code changes

### ISSUE THREAD

**Issue by LucianoBestia** [microsoft/codetour#53] opened 2020-04-22 09:37 UTC
The tour step has this data to identify file + line number:  
`"file": "webfolder/mem6/index.html",  
"line": 82,`  
Line numbers can change a lot adding and changing code.   
You call this "tour decay", or "line number out of sync".
If you add to the step the text of the line in the code like this:  
`"line_text":"<script type='module'>"`  
Then you can :
1. check if all the steps line numbers are still in sync with the code file line numbers
2. If the changes are small, you can automatically find the nearest line with the text and update the line number.
3. If you can not find the text, then it is an orphan and the line number needs manual fixing
 
Thank you for this great extension. This is the most natural way to introduce complex code to a programmer. And your extension and its user interface is great. Good job !

**Comment by gsmile** [comment] 2020-04-22 21:12
Hi Luciano, thanks for the suggestion! This would be a useful addition. We will look into adding this to CodeTour!

**Comment by awilkins** [comment] 2020-06-01 11:18
Another potential way of handling this (if we call this method the "patch context line" method) ; keep a watch on all the files in current tours in the workspace, and bump the line markers when edit events occur.

I think there's a place for both methods (context lines, and event handling, not least because not all edits may occur in VSCode with a code tour extension enabled.)

**Comment by LucianoBestia** [comment] 2020-06-02 09:40
I know that this topic is controversial, but it needs to be debated. 
This functionality  could be opt-in, so it doesn't bother the people that don't like it. 
Most of the files for a tour steps are source code. It would be beneficial to insert there a special line comment. 
I know that it is undesirable that an editor messes with your source code.  But probably is not so intrusive, because that part of the code surely already has comments. And this new one is talking exactly about the code there. This would be 100% exact to position the tour steps.
But some people really dislike it and they should have the possibility to disable this function.
There are also some types of files where comments don't exist (json) or are not suitable for tour use.
Probably it will best to have all 3 mechanisms:
1. write a "meaningful" comment on the right place in source code
2. use the file+line data, but check if the line is still exactly the same. First you need to store the original line.
If is not, try to find it in the neighborhood. Else the developer must find it manually.
File watching is always nice and dynamic. But not always possible as you mentioned.

**Comment by alpaix** [comment] 2020-06-05 21:12
+1 on sticky tags in the source code.

A *decayed* code tour issue is a very frustrating experience. I'd prefer to have an option to bind a tour step to a code syntax element, e.g. class, function or variable, rather than a line in file. Although, it might be quite expensive to implement.

A cheaper alternative could be having some sort of convention on code tour annotations in code. Similar to `TODO:`, `FIXME:` and so on. The annotation can include a step ID referenced to this particular location.
```js
// TOUR:23
function activate(context) {
}
```

I agree this is more intrusive. Yet, it might be a reasonable compromise.

**Comment by LucianoBestia** [comment] 2020-06-16 12:19
Please, make it optional to opt-in to sticky-tags. Separate for file extension. 
I need for *.rs.
Now it is unusable. My line numbers are changing all the time.
The steps have titles. 
These could be duplicated in the code comments to have a human readable anchor.

![image](https://user-images.githubusercontent.com/31509965/84772911-435b5d00-aff9-11ea-979e-0f51aa0a421d.png)

That does not look bad.


![image](https://user-images.githubusercontent.com/31509965/84772584-c4febb00-aff8-11ea-8d2f-e1742dfa0d66.png)

**Comment by awilkins** [comment] 2020-06-17 07:51
I have also noticed : if you attach the tour to a specific commit or branch, the "Tour Guide" will pull that version of the resource from the repo to tour you around it. This provides a perfectly stable "tour site" but of course, it may drift from the current state of the code. Swings/roundabouts!

**Comment by lostintangent** [comment] 2020-06-28 22:08
@awilkins Yep, I added the ability to associate a tour with a specific branch/tag/commit to enable the tour to be stable. That said, I’m using this issue to track the work to enable “rebasing” the tour as needed.

**Comment by bpmct** [comment] 2020-12-02 22:48
I know the folks at @TeamCodeStream have solved this in their extension. Perhaps there is room for some sort of collaboration?

**Comment by lostintangent** [comment] 2021-03-10 20:34
Closing this as a duplicate of #141, which is tracking the work to record steps, which are associated to "patterns" of code, not the actual line number.

**Closed by lostintangent** 2021-03-10 20:34 UTC
Labels: P1, area: recording, enhancement
