### ISSUE TITLE
Previewing a step after editing it (without clicking the save button) erases changes

### ISSUE THREAD

**Issue by dsschnau** [microsoft/codetour#138] opened 2021-02-23 20:07 UTC
1. Edit a CodeTour step
2. Click the 'Preview Tour' button in the step window
3. See that the edits aren't rendered
4. Go back to 'edit step'
5. Changes from step 1 are gone

**Comment by gsmile** [comment] 2021-02-25 16:20
Thank you for this suggestion. I can see that it would be annoying to lose your work. We will look into prioritizing this issue.

**Comment by lostintangent** [comment] 2021-02-25 20:23
Upon investigation, there seems to be a bug in VS Code that would prevent us from saving the contents, unless you click one of the "big buttons" beneath the text box. That said, if we address https://github.com/microsoft/codetour/issues/140, would that be sufficient to start? Then, you could simply save your step and enter preview mode, as opposed to needing to enter preview mode and have it save your step?

**Comment by gsmile** [comment] 2021-02-26 16:18
That can be a great start. Anything we can do to prevent loss of work would be great.

**Comment by lostintangent** [comment] 2021-03-09 21:06
#140 is now addressed, and so that should help mitigate this issue a bit? Unfortunately, I'm not able to resolve this further without an ask on VS Code.

**Comment by lostintangent** [comment] 2021-03-28 23:21
I'm going to close this as a duplicate of #110.

**Closed by lostintangent** 2021-03-28 23:21 UTC
Labels: P1, VS Code Ask, area: recording
