### ISSUE TITLE
Add Tour Step doesn't provide a place to enter text

### ISSUE THREAD

**Issue by codykonior** [microsoft/codetour#129] opened 2021-02-10 01:35 UTC
I haven't been able to get Tour Step to work.

1. Click Record Tour.
2. Create a title "Backups" and associate with None
3. Right click CodeTour / Backups, and Add Tour Step
4. Give it a title of Introduction

It adds the step but the documentation says this should create a virtual file to contain some text. But I don't get a new pane to enter any markdown, and no amount of clicking and right clicking on it seems to do anything.

VS Code 1.53.1
CodeTour 0.0.43

**Comment by lostintangent** [comment] 2021-02-10 04:04
Hey! This is a duplicate of the issue in #128. I'm about to publish the fix for this right now, and so I'll update that issue once it's available. In the meantime, I'm going to close this as a duplicate. Apologies for the inconvenience!

**Closed by lostintangent** 2021-02-10 04:04 UTC
