### ISSUE TITLE
Fix compatibility with JAWS

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#147] opened 2021-03-10 19:31 UTC
CodeTour/VS Code does not allow use of the virtual PC cursor when using JAWS, which makes this toolset unusable for people who use JAWS. 

We would like to allow the use of the virtual PC cursor when using CodeTour/VS Code as opposed to the current experience of navigating through tabbed items only.

**Comment by lostintangent** [comment] 2021-03-20 02:51
Closing as a duplicate of #136.

**Closed by lostintangent** 2021-03-20 02:51 UTC
Labels: P1
