### ISSUE TITLE
Accessibility: Bigger buttons to move forward and back

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#104] opened 2020-11-06 23:56 UTC
We've received feedback that the forward and back buttons for CodeTours are not very visible. Now there are links implemented. We have received feedback that during code presentations, developers would like large "hero carousel" buttons to move back and forth between steps. This is especially useful for people who may have learning differences or preferred ways to view code.

**Comment by lostintangent** [comment] 2020-11-07 02:33
Unfortunately, I don't think we'll have much flexibility for addressing this. I wonder if the notebook view that we experimented with would help here? Since the user could see the entire tour in a top-to-bottom fashion?

**Comment by gsmile** [comment] 2020-11-07 20:27
Is there a way to enlarge the forward/back buttons at all? I've heard this piece of feedback many times now, from a student learning perspective as well as a developer code presentation perspective. Perhaps we can keep brainstorming to see how to make the forward/back buttons more visible.

**Comment by lostintangent** [comment] 2020-11-07 23:42
Yeah based on the current support we have from VS Code, I don't believe there's any way for us the enlarge the forward/back buttons. Do you new previous/next links help at all? I know that we had a lot of feedback that the buttons in the title bar weren't very discoverable, and so I was just curious if we could get feedback from users now that we just added these new links.

**Comment by gsmile** [comment] 2020-11-08 00:00
That's a good point. 
I've gotten feedback that the prev/next links don't help in the following scenarios:
- When CodeTours are already established in a repo and don't have titles for prev/back links, things look ugly, and it's annoying to go back and fix everything. Perhaps there's a way to optimize for repos that don't have CodeTour titles as well?
- People who have learning differences need something standing out to click when presenting code, like enlarged arrows, because they are already under pressure to present and can't handle aiming for small arrow keys. Perhaps we can brainstorm on how to help in this scenario.

**Comment by lostintangent** [comment] 2020-11-08 00:03
To address point #1: we could change the next/previous links to only display the step's title if it's actually defined, and otherwise, don't show the file name that's associated with the step. That would seemingly help? If that makes sense, then I could make that change tonight.

**Comment by gsmile** [comment] 2020-11-08 00:04
That sounds perfect!

**Comment by lostintangent** [comment] 2020-11-08 17:44
@gsmile I just pushed an update that only only shows the step title in the next/previous links, if the step actually has a title. That should address issue #1 above.

**Comment by gsmile** [comment] 2020-11-09 02:34
That's wonderful, thank you!

**Comment by lostintangent** [comment] 2020-12-13 20:21
@gsmile Now that we fixed the tour titles in links, what’s your thoughts on the next steps for this issue? I don’t think we currently have any way to make the navigation links bigger unfortunately, and so the primary workaround would be for the user to zoom VS Code. Otherwise, we may need to spec out the behavior we want and see if we need to make any asks on VS Code.

**Comment by gsmile** [comment] 2020-12-15 01:24
Is there an ask where we can increase the size of the icons in the tour step?

**Comment by lostintangent** [comment] 2020-12-15 03:25
I think this would end up being the same ask as we're discussing in #111. That said, since we're going to deprioritize the presentation scenario for now, we can probably revisit this item when we focus on it in the future?

**Comment by lostintangent** [comment] 2021-03-20 02:41
Closing this as a duplicate of #111.

**Closed by lostintangent** 2021-03-20 02:41 UTC
Labels: P3, area: view
