### ISSUE TITLE
Add option to create CodeTour from blank file/folder

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#115] opened 2020-11-13 21:27 UTC
We want to start enabling scenarios where instructors begin to create lessons right within CodeTour, as opposed to an existing codebase.

To start doing this, developers need an option to add a CodeTour to a blank file, or to start a CodeTour step without code. Currently, this option does not exist.

We can look into injecting steps or tours dynamically into blank files; when the file or repo is blank, the CodeTour tree can present the option to start a tour or step.

![image](https://user-images.githubusercontent.com/12738587/99122515-7287f180-25cc-11eb-8ff1-c82a6f078038.png)

**Comment by lostintangent** [comment] 2020-11-20 05:36
What’s your thoughts on the expected behavior in this case? Currently, when you create a new tour, the underlying file is written to the opened directory. But if you don’t have a directory opened, then where would we want to store the tour file? 

Also, if you don’t have a folder open, the only kind of steps you could add are “content steps” (since there aren’t any folders or files to annotate). So would we want to somehow make this workflow smoother, by detecting the empty workspace and auto-adding a new content step when you create a tour?

**Comment by gsmile** [comment] 2020-11-23 17:38
I think at the very least, the CodeTour tab needs to be available for the developer to see and click. If there's no directory open, is there the possibility of creating the .tours folder in a cache and dumping it when the developer finally saves or commits?

We could also force save before creating a tour step. That would probably be the simplest route right? Or we could pop up a notification saying that the user would have to save in a directory to create a tour step?

**Comment by lostintangent** [comment] 2020-12-13 20:06
While we could create the tours directory in a cache, if the developer didn’t have a folder open, they wouldn't be able to add steps to any files, since the tour steps need to be associated with a folder. 

The current workaround for this would be to simply create an empty directory and open it in VS Code. That seems potentially sufficient, since the tour author would need to create a Git repo to store their tours anyways?

**Comment by gsmile** [comment] 2020-12-15 01:36
Can CodeTour create that empty directory and opening in VS Code, along with creating that initial step? I think this is the first foray into creating CodeTours from blank files or tutorials. 

I'm going to reprioritize this item since it looks like we're getting traction in other areas right now, not necessarily creating tutorials from scratch. I think the new workflow is unnecessary since we are getting traction for an existing workflow. :)

**Comment by lostintangent** [comment] 2020-12-15 03:05
Yeah we could definitely create and open the new directory. That said, I agree with your reprioritization, so we can maybe hold off on doing anything here until we revisit this use case?

**Comment by gsmile** [comment] 2020-12-17 18:13
That sounds good to me.

**Comment by lostintangent** [comment] 2021-03-20 16:57
I'm going to close this for now, since we aren't prioritizing this scenario. We can always re-open it if/once we hear more feedback 👍🏻

**Closed by lostintangent** 2021-03-20 16:57 UTC
Labels: P3, area: recording
